### ISSUE TITLE
Gulp process

### ISSUE THREAD

**Issue by MichalNowacki** [spicecrm/spicecrm_fe_release_core#12]
Hi,

I have studied gulp files and I have some problem.

First of all I would like to describe how it works. In my opinion of course :)
In order to build application for production we have to run few gulp tasks.
First task is js:build and it works ok.
Second step is run type script compile to create .js files. The step prints a lot of errors, some of them is releated to "groupware". (I get new errors after pull changes from repository ` Argument of type '{ read: typeof ViewContainerRef; static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.`)
Next is js:uglify. It should move files to ./app.
After all I should run js:release_core to get folder with my production.

Is my process ok?
Could you help me with tsc after js:build?

I have to change path to plugins from
`var embedComponents = require('gulp-spicecrm-embed-components');`
to
`var embedComponents = require('./gulp-plugins/gulp-spicecrm-embed-components');`
and slashes in gulpfile.js:124
`                .pipe(embedComponents({basePath: __dirname + '/src/' + module.directory}))`

**Comment by christianknoll** [comment]
- the manual fix currently required for the groupware service we are aware about. This is embedded too often. So the Goupware needs a quick manual fix
- the Viwechild decorator issue should be fixed if you pull the latest version from the dev repository. This was due to the Angular 8.0.1 upgrade
- after js:build and tsc run js:uglifyfromreference ... this ensures that the uglify does not mess up the required dynamic components
- you can also copy the custom gulp plugins to the node_modules directory then no parth needs to be changed
- the slashes in the gulpfile line 124 I am not aware about and have not seen that issue before.
