### ISSUE TITLE
Kanban view - Missing Stages

### ISSUE THREAD

**Issue by szymon-ryddza** [spicecrm/spicecrm_fe_release_core#15]
While working on Polish translations for Kanban view I've discovered that some stages are missing for different modules:
- For Opportunities we can't see Closed Lost and Closed Discontinued
- For Tasks we can't see In Progress stage (column in Kanban view)
- For Leads we can't see Closed Dead stage

I've checked it out on two separate instances and this (potentialy) bug occures on both.
Is this an intentional behaviour or is it an actual bug?

**Comment by christianknoll** [comment]
this is intentional - the stages that are displayed can be configured and set in the spicebeanguide tables. That should be set to match the definition of stages for a customer and also for the stages you want to see. 

e.g. for the opportunities the closed is a grouped step that combines the different closed stages. All three stages are closed but with a slightly different flavor. 

e.g. for Leads: you will get a high number of "Dead Leads" and in order to focus on the ongoing work the dead stage is not showing. 

but as stated - that is up to the customer and project to configure that according to their needs and stages.
